### ISSUE TITLE
不支持SSR对吗？

### ISSUE THREAD

**Issue by Taering365** [falseen/PySocket#9]
吧文件放到SSR目录下，总是报错

**Comment by falseen** [comment]
@Taering365 报什么错 ？

**Comment by Taering365** [comment]
2017-04-07 08:43:59 ERROR    server_pool.py:87 too many values to unpack
Traceback (most recent call last):
  File "/test/shadowsocksr/server_pool.py", line 80, in _loop
    loop.run()
  File "/test/shadowsocksr/shadowsocks/eventloop.py", line 217, in run
    handle = handle or handler.handle_event(sock, fd, event)
  File "/test/shadowsocksr/shadowsocks/tcprelay.py", line 1274, in handle_event
    conn = self._server_socket.accept()
  File "/test/shadowsocksr/socket.py", line 74, in <lambda>
    types.MethodType(lambda *args, **kwds: new_method(method, *args, **kwds), None, _class))
  File "/test/shadowsocksr/socket.py", line 93, in new_accept
    client_ip, client_port = return_value[1]
ValueError: too many values to unpack


提示这个错误！

**Comment by falseen** [comment]
@Taering365
我刚更新了下代码，你更新一下试试。另外，ssr我是测过的，只不过我测的是单用户版，即shadowsocksr目录里面的server.py。多用户版我稍后再测试一下，你也可以先用单用户版试试看还会不会报错。这个错误挺奇怪的。

**Comment by falseen** [comment]
@Taering365 
额，找到原因了。可能是ssr更新了代码，再加上原来的代码本身就有一些疏漏。所以导致了这个问题。

现在已经修复了，你更新代码就行了。

**Comment by Taering365** [comment]
好的，非常感谢！

**Comment by Taering365** [comment]
Traceback (most recent call last):
  File "/test/shadowsocksr/server_pool.py", line 80, in _loop
    loop.run()
  File "/test/shadowsocksr/shadowsocks/eventloop.py", line 217, in run
    handle = handle or handler.handle_event(sock, fd, event)
  File "/test/shadowsocksr/shadowsocks/tcprelay.py", line 1274, in handle_event
    conn = self._server_socket.accept()
  File "/test/shadowsocksr/socket.py", line 101, in <lambda>
    setattr(self, method_name, types.MethodType(lambda *args, **kwds: new_method(method, *args, **kwds), self, self))
  File "/test/shadowsocksr/socket.py", line 110, in new_accept
    client_ip, client_port = return_value[1]
ValueError: too many values to unpack


问题依旧 
debian7 64   破娃酱SSR原版

**Comment by falseen** [comment]
@Taering365 
应该是ipv6的原因。再更新一次试试。

**Comment by Taering365** [comment]
明白，我再试试！

**Comment by Taering365** [comment]
):
  File "/test/shadowsocksr/db_transfer.py", line 242, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/test/shadowsocksr/db_transfer.py", line 377, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 412, in _connect
    self._request_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 443, in _request_authentication
    self._send_authentication()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 486, in _send_authentication
    auth_packet = MysqlPacket(self)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/packet.py", line 62, in __init__
    self.__recv_packet()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/packet.py", line 81, in __recv_packet
    packet_header = self.__recv_from_socket(4)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/packet.py", line 74, in __recv_from_socket
    raise OperationalError(2013, "Lost connection to MySQL server during query")
OperationalError: (2013, 'Lost connection to MySQL server during query')


更新代码后

**Comment by Taering365** [comment]
好像好了！ 但是客户端一链接后，
2017-04-08 19:02:05 ERROR    shell.py:50 [Errno 22] Invalid argument
2017-04-08 19:02:05 ERROR    shell.py:50 [Errno 22] Invalid argument
2017-04-08 19:02:05 ERROR    shell.py:50 [Errno 22] Invalid argument
2017-04-08 19:02:08 ERROR    shell.py:50 [Errno 22] Invalid argument

每次刷新u2be，产生数据请求后就这样

**Comment by falseen** [comment]
加上 -v 参数，看看是哪个语句报的错。

**Comment by Taering365** [comment]
2017-04-08 19:16:33 DEBUG    db_transfer.py:184 db allow users {30000L: 'pwd', 30001L: 'pwd'} 
mu_servers {}

**Comment by falseen** [comment]
不是这个。

**Comment by Taering365** [comment]
只有这个啊！

**Comment by Taering365** [comment]
上面还有一行这个，
2017-04-08 19:24:36 DEBUG    shell.py:171 loading config from config.json

**Comment by falseen** [comment]
那这个应该是ssr的问题。。

**Comment by Taering365** [comment]
好的，谢谢了！
